name: Check for broken links

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "source/**"

jobs:
  check_links:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v3
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: htmlproofer
        run: /scripts/check-url-links.sh
