# Ignores known non-critical statuses: 200, 400, 401, 402, 403, and 429.
# Still checks external links to catch genuine 404s, but may need manual review. 
# External links causing false-positives by throwing 404s will be allow-listed soon.
name: Check links (Flexible)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'source/**'

jobs:
  check-links-flexible:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v3
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install dependencies
        run: bundle install
      - name: Build site
        run: bundle exec middleman build --build-dir docs --relative-links
      - name: Run HTMLProofer (Flexible)
        run: |
          htmlproofer ./docs --http-status-ignore "400,401,402,403,429" --allow-missing-href true
