name: Publish

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/cloud-platform-user-guide:2.2
    steps:
      - uses: actions/checkout@master
      - run: ruby bin/publish.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
